[theme]
primaryColor = "#6675e0"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#e0e5ff"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
